version: '3.3'

services:
  mysql:
    image: mysql:5.7-oracle
    restart: always
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: social_media
      MYSQL_ROOT_PASSWORD: root
